### ISSUE TITLE
State snapshot in URL doesn't work

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#284]
When calling Vidi with `state=state_snapshot_......` in URL the snap shot is not activated.
![image](https://user-images.githubusercontent.com/3850918/55147205-434a1580-5146-11e9-9751-a2ad242a7850.png)
![image](https://user-images.githubusercontent.com/3850918/55147217-47763300-5146-11e9-9c74-e6cbbb1766e4.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/00f61d32aaf2def2f0cf4695dc56086475534653

**Comment by mapcentia** [comment]
@sashuk this issue seems to still exists:
![image](https://user-images.githubusercontent.com/3850918/55288266-426aeb00-53b5-11e9-8b02-baf7fe5bb9cb.png)
![image](https://user-images.githubusercontent.com/3850918/55288267-4860cc00-53b5-11e9-8e5c-66f0de65bd9f.png)

**Comment by sashuk** [comment]
@mapcentia Could you please check if https://vidi.swarm.gc2.io has the latest code? Looks like the source is still old, as latest changes are not applied.

**Current source at https://vidi.swarm.gc2.io:**

![temp](https://user-images.githubusercontent.com/1390758/55304235-08651c00-547d-11e9-87e8-12038ea54bcd.png)


**Latest changes:**

https://github.com/sashuk/vidi/blob/00f61d32aaf2def2f0cf4695dc56086475534653/browser/modules/stateSnapshots/index.js#L11-L19

**Comment by mapcentia** [comment]
@sashuk It was a update issue on the swarm host. Sorry
